title: Researcher
url: "home.jianzhong.cn"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/pkuCactus"
footer_text: "Page design by Jianzhong He"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"

theme: jekyll-theme-time-machine